settings:
  wp_path: /Users/williampetruzzo/Sites/Petruzzo-Staging-Rebuild
  apply_taxonomy:
    mode: all  # Options: all, children_only, bottom_only
  backup:
    enabled: true
    output_path: /Users/williampetruzzo/Sites/backups_staging_rebuild/media-categorizer-$(date +%F_%H-%M-%S).sql
  output_csv_path: ./logs/media-categorizer-log-$(date +%F_%H-%M-%S).csv

mappings:
  Formals:
    match: "Formals"
    terms:
      - Wedding > Portraits
  Candids:
    match: "Candids"
    terms:
      - Wedding > Preparations
  Ceremony:
    match: "Ceremony"
    terms:
      - Wedding > Ceremony
  Details:
    match: "Details"
    terms:
      - Wedding > Details
  Party:
    match: "Party"
    terms:
      - Wedding > Party
  Portfolio:
    match: "Portfolio"
    terms:
      - Wedding > Portfolio
